### ISSUE TITLE
Trigger action without text required

### ISSUE THREAD

**Issue by Skyass** [zfox23/twitchChatListener#1]
Hey, first off i am not into python or any other programming languages. I know a few things which I taught myself pretty much.
However, I looked for some kind of tool to trigger keys from my keyboard through channel redemptions and I just found your script. It did not work at the start and I figured out pretty quickly that the script only notices redemptions which "Require Viewer to Enter Text". With that requirement enabled everything works fine but I actually want the action to be triggered without forcing my viewers to type something in there.

Is it possible to adjust the script so that the action triggers without the text?
I would appreciate this change very much and think future users of this script could also benefit from it.

However, good work so far and keep it up SeemsGood

Edit: Happy new year :)

**Comment by zfox23** [comment]
Hey @Skyass! Thanks for your interest in my script.

Unfortunately, I can't change any of the code in this repository to work around the requirement that users must enter text to redeem channel point rewards that trigger actions on your local machine. Please read this repo's README for more information. Sorry!

Happy new year to you as well :)
